### ISSUE TITLE
memory showing tb and icons only

### ISSUE THREAD

**Issue by KaosCreator69** [Anachron/i3blocks#35] opened 2017-03-01 04:15 UTC
Hey me again, this time I have a need for keeping track of memory and swap. I've run everything as per your examples;
[memory]
command=~/.config/i3/scripts/memory
label=
instance=mem;free
interval=30

[memory]
command=~/.config/i3/scripts/memory
label=
instance=swap;total
interval=30

Made sure to chmod the memory script under scripts, but it will only show a value of tb.

Any ideas?

**Comment by KaosCreator69** [comment] 2017-03-12 02:35
Anyone have an idea why I cannot get data to show, numbers representing the amount of memory and swap? instead of the letters 'tb' for both.

**Comment by Anachron** [comment] 2017-03-12 07:56
I'll see if I can reproduce and give you a reply.

**Comment by insuusvenerati** [comment] 2017-05-12 21:46
Seems to be related to 
```
ONE_MB=$(echo "${ONE_KB}*1024" | bc -l)
ONE_GB=$(echo "${ONE_MB}*1024" | bc -l)
ONE_TB=$(echo "${ONE_GB}*1024" | bc -l)
```
in the memory script. When running the script in terminal I get
```
./memory: line 21: bc: command not found
./memory: line 22: bc: command not found
./memory: line 23: bc: command not found
./memory: line 41: bc: command not found
./memory: line 42: bc: command not found
./memory: line 56: bc: command not found
./memory: line 59: bc: command not found
tb
tb
```

Running `sudo pacman -S bc` fixed the issue :P

```
❯ ./memory                  
12.31gb
12.31gb
```

**Comment by vKnmnn** [comment] 2017-09-13 22:37
if this is fixed, you should close the issue.

**Comment by insuusvenerati** [comment] 2017-09-14 13:35
@KaosCreator69

**Closed as completed** 2020-02-08 13:25 UTC
